### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by jtcarnes** [hashicorp/vault-plugin-database-redis#3]
@fhitchen Love the plugin. I find myself in the same situation you did.

I'm curious if you've thought of making it available to the community at <https://www.vaultproject.io/docs/plugins/plugin-portal#community>
or creating releases/tags of the plugin.

Love to help out if you're no longer interested in maintaining.

**Comment by fhitchen** [comment]
Hi,

Thanks for the feedback. I will certainly go and make it available. I
thought that there was no real use case for it though as I got little
interest from the Vault team. However you are the second person to give me
feedback, so thanks for the pointer to the community page.

Regards, Francis.

**Comment by fhitchen** [comment]
Hi,

I just noticed REDIS Labs have added their own Vault plugin on the plugin
portal page. Would you not prefer it over this one?

Regards, Francis.

**Comment by jtcarnes** [comment]
Hello Francis,

From what I understood (and correct me if I'm wrong) is that their plugin only worked with redis enterprise and not open source redis? Or did I read that wrong.

**Comment by maltegrosse** [comment]
@jtcarnes I understood the same so far.

Would be great to see your plugin in the offical repo - or is it possible to provide some multi-arch binary releases?
e.g. with github actions: https://github.com/alexellis/hey-redist/pull/1/files

**Comment by fhitchen** [comment]
Hi @maltegrosse, @jtcarnes I did submit this to the Vault community plugin page to see if they would publish it there and they actually want to take it over and use it as their own REDIS DB plugin!

**Comment by hsimon-hashicorp** [comment]
> Hi @maltegrosse, @jtcarnes I did submit this to the Vault community plugin page to see if they would publish it there and they actually want to take it over and use it as their own REDIS DB plugin!

Huzzah! Since this has happened, I'm going to go ahead and close this issue. If you have bug reports or feature requests, please feel free to open a new issue. Thanks so much for your contribution, @fhitchen!

**Comment by fhitchen** [comment]
Hi,

Hmm, maybe. I wonder how different the Enterprise cluster is to a build
your own one. I'll request to add it there and see what happens.

regards, Francis.
